[package]
name = "twofa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.12"
sha-1 = "0.10"
totp-lite = "2.0.0"